USERS = [
    {"id": 1, "full_name": "Admin User", "email": "admin@skillfort.test", "password": "admin123", "role": "admin"},
    {"id": 2, "full_name": "Student User", "email": "student@skillfort.test", "password": "student123", "role": "student"},
]

COURSES = [
    {
        "id": 1,
        "slug": "full-stack-mastery",
        "title": "Full Stack Web Development Mastery",
        "thumbnail": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80",
        "price": 44999,
        "discountPrice": 24999,
        "category": "Full Stack Training",
        "instructor": "Arun Prakash",
        "lessonsCount": 92,
        "studentsCount": 410,
        "rating": 4.8,
        "status": "published",
        "createdAt": "2026-01-10",
    },
    {
        "id": 2,
        "slug": "python-placement-bootcamp",
        "title": "Python Placement Bootcamp",
        "thumbnail": "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=900&q=80",
        "price": 19999,
        "discountPrice": 14999,
        "category": "Python",
        "instructor": "Priya N",
        "lessonsCount": 64,
        "studentsCount": 295,
        "rating": 4.7,
        "status": "published",
        "createdAt": "2026-02-18",
    },
    {
        "id": 3,
        "slug": "oracle-database-admin",
        "title": "Oracle Database Administration",
        "thumbnail": "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=900&q=80",
        "price": 18999,
        "discountPrice": 12999,
        "category": "Oracle",
        "instructor": "Karthik M",
        "lessonsCount": 55,
        "studentsCount": 170,
        "rating": 4.6,
        "status": "published",
        "createdAt": "2025-12-02",
    },
    {
        "id": 4,
        "slug": "dummy-course",
        "title": "Dummy Test Course",
        "thumbnail": "https://example.com/dummy.jpg",
        "price": 0,
        "discountPrice": 0,
        "category": "Test",
        "instructor": "Test",
        "lessonsCount": 1,
        "studentsCount": 0,
        "rating": 0,
        "status": "draft",
        "createdAt": "2024-01-01",
    },
]

QUESTIONS = [
    {
        "id": 101,
        "slug": "maximum-subarray-kadane",
        "title": "Find maximum subarray sum (Kadane's Algorithm)",
        "difficulty": "medium",
        "domain": "DSA",
        "type": "coding",
        "tags": ["arrays", "dynamic-programming", "kadane"],
        "companies": ["Amazon", "Google", "Zoho"],
        "views": 1840,
        "bookmarks": 512,
        "body": "Given an integer array nums, find the contiguous subarray with the largest sum and return its sum.",
        "hint": "Track current best while scanning the array once.",
        "answer": "Kadane's algorithm with O(n) time and O(1) space.",
        "boilerplate_py": "def max_subarray(nums):\n    # Your solution here\n    pass",
        "test_cases": [
            {"input": "[-2,1,-3,4,-1,2,1,-5,4]", "expected_output": "6"},
            {"input": "[1]", "expected_output": "1"},
        ],
    },
    {
        "id": 102,
        "slug": "design-url-shortener",
        "title": "Design a URL Shortener",
        "difficulty": "medium",
        "domain": "System Design",
        "type": "design",
        "tags": ["hld", "hashing", "redis"],
        "companies": ["Amazon", "Freshworks"],
        "views": 1211,
        "bookmarks": 322,
        "body": "Design a URL shortening service with analytics and high-scale redirects.",
        "hint": "Cover API, DB schema, and short-code generation.",
        "answer": "Use Base62 keys, Redis cache, and write-optimized analytics.",
        "boilerplate_py": "# discuss architecture",
        "test_cases": [],
    },
]

TOPICS = [
    {"id": 1, "slug": "dynamic-programming", "name": "Dynamic Programming", "domain": "DSA", "description": "Optimize recursive problems with memoization/tabulation."},
    {"id": 2, "slug": "rest-api-design", "name": "REST API Design", "domain": "Full Stack", "description": "Design resilient web APIs for scale."},
]

COMPANIES = [
    {"id": 1, "name": "Google", "slug": "google", "logo_url": "", "interview_process": "Coding + System design + Googliness"},
    {"id": 2, "name": "Amazon", "slug": "amazon", "logo_url": "", "interview_process": "DSA + Leadership principles"},
    {"id": 3, "name": "TCS", "slug": "tcs", "logo_url": "", "interview_process": "Aptitude + Technical + HR"},
]
